// Sticky notes of every NovaTech workflow, in one place. Markdown; the size is computed from the text (lib.mjs
// fitStickies), so a note always shows its full content. Colors: 4 green = overview of an entry point,
// 5 blue = overview, 6 purple = candidate-facing, 3 pink = manual setup needed in n8n.
const lines = (...l) => l.join('\n');

export const NOTES = {
  'WF-00': [lines(
    '## WF-00 Dispatcher & Scheduler',
    '**Durable timers + transactional outbox.** Every status change writes its follow-up into `ops.scheduled_actions` in the same database transaction; reminders and expiries are rows with a future `run_at`.',
    '',
    '### How a run works',
    '1. Claim due rows with `FOR UPDATE SKIP LOCKED` (overlapping runs are safe).',
    '2. Route each action to its owning workflow (table in **Route by Action Type**).',
    '3. Record **DONE**, **SKIPPED** (state moved on) or **FAILED**.',
    '',
    '### Failures',
    '- FAILED is retried with exponential backoff (30 s up to 1 h).',
    '- After the last attempt the action lands in the error queue (WF-07, replayable).',
    '',
    '### Triggers',
    '- Every minute (safety net).',
    '- **Kick Webhook** `POST /webhook/ops/kick`: the backend calls it right after a person acts.',
    '- **When Kicked by Workflow**: intake and replays start it immediately.',
  ), 4],

  'WF-01': [lines(
    '## WF-01 Application Intake',
    'Public entry point: `POST /webhook/applications` (the careers page). Requires an **Idempotency-Key** header.',
    '',
    '### Steps',
    '1. `api.register_event` stores the raw payload first: nothing is silently dropped and a correlation id is assigned.',
    '2. A replay of a completed event returns **200** with the original result and creates nothing.',
    '3. Otherwise it answers **202** at once, validates through **SWF-01** (with retries) and stores through **WF-02**, which emails the acknowledgement.',
    '4. If validation still fails after the retries, the event is marked FAILED and goes to the error queue; a replay redelivers the same key and body.',
    '',
    '`X-Fault-Inject` (development only) is passed to the backend for the failure demos.',
  ), 4],

  'WF-02': [lines(
    '## WF-02 Candidate Processing',
    'Stores every submission and makes sure the candidate **hears from us at every step**.',
    '',
    '### Intake (called by WF-01)',
    '- `api.submit_application` runs one transaction: candidate upsert, duplicate check, application `NEW → VALIDATING → VALIDATED / SCREENING_REVIEW`.',
    '- A replayed event returns its stored result; the acknowledgement goes out once per event (SWF-02 dedupe key).',
    '',
    '### Rejection notice (`SEND_REJECTION_NOTICE`)',
    '- Re-checks that the application is still `REJECTED` before emailing.',
    '',
    '### Status updates (`NOTIFY_CANDIDATE`)',
    '- Queued by the database together with the status change (`application_statuses.candidate_notice`): under review, interview completed, selected, onboarding finished, withdrawn.',
    '- Skipped when a later step already emailed the candidate, so emails never arrive out of order.',
    '- Internal reasons are never part of a candidate email.',
    '',
    'Failures go to SWF-03 with replay target WF-02.',
  ), 6],

  'WF-03': [lines(
    '## WF-03 Scoring & AI Review',
    'Runs for the action `SCREEN_APPLICATION` (application entered VALIDATED).',
    '',
    '### Steps',
    '1. **Re-check**: continues only if the application is still VALIDATED.',
    '2. **Rule score**: the backend reads the scoring rules from the database (data-driven); `api.record_application_score` moves it to SCORED.',
    '3. **Advisory AI** (Mistral, backend key): a validated analysis, or FALLBACK when the model is unavailable or its answer is malformed. Stored with `api.record_ai_analysis`.',
    '4. **Decision policy**: the rules decide and the AI can only add a human review. `api.apply_screening_decision` moves it to SHORTLISTED, SCREENING_REVIEW or REJECTED.',
    '',
    '### Failures',
    '- Retryable: returns FAILED, the dispatcher retries with backoff.',
    '- Permanent: error queue, replay target WF-03.',
  ), 5],

  'WF-04': [lines(
    '## WF-04 Interview Management',
    'Called by **WF-00** for interview actions. Every branch re-checks the current state first; a stale timer is **SKIPPED**.',
    '',
    '### Invitation',
    '- `api.create_interview_invitation` (idempotent per round; schedules reminder and expiry) → signed slot link → email to the candidate.',
    '',
    '### Booking',
    '- The candidate picks a slot in the portal (`api.confirm_interview_slot`).',
    '- This workflow records the calendar event, confirms to the candidate and briefs the interviewer with a scorecard link.',
    '- **AI interview questions**: n8n\'s own Mistral credential drafts 5 role-specific questions for the brief (no personal data; the brief is sent without them if the model is unavailable).',
    '',
    '### Feedback',
    '- Reminder, then escalation to HR. Submitting the scorecard (link or HR portal) cancels both timers.',
    '',
    '### Evaluation',
    '1. **AI interview assessment** (backend, Mistral): reads ratings, comments and screening results; recorded with `api.record_interview_assessment`.',
    '2. **Weighted score** (30 % screening + 70 % interview; weights and thresholds are settings).',
    '3. The AI can only add a hiring-manager review (disagreement, or comments that contradict the ratings) → `api.apply_interview_decision`.',
    '',
    'Retryable failures return FAILED (dispatcher backoff); permanent ones go to the error queue (SWF-03). Emails are sent at most once per dedupe key.',
  ), 5],

  'WF-04-setup': [lines(
    '## Setup: Mistral credential',
    'The node **Mistral Chat Model** uses the n8n credential **Mistral AI (n8n)**, with n8n\'s own key (not the backend key).',
    '1. Put the key in `.env` as `N8N_MISTRAL_API_KEY`.',
    '2. Run `sh scripts/n8n-mistral-key.sh` (Windows: `scripts\\n8n-mistral-key.ps1`). Or: **Credentials** → **Mistral AI (n8n)** → paste the key → **Save**.',
    '',
    'Model: `ministral-8b-latest`. Mistral limits apply per workspace and per model; the backend uses `ministral-14b`, so this model has its own budget (188 requests/min on a free key). Without a key the interviewer brief is still sent, just without the suggested questions.',
  ), 3],

  'WF-05': [lines(
    '## WF-05 Offer Management',
    'Called by **WF-00** for offer actions; every branch re-checks the offer and application state first.',
    '',
    '### Draft (`api.create_offer`)',
    '- Salary: the expected salary, clamped to the position band.',
    '- Above `offer.second_approval_threshold` two approval levels are required.',
    '- After an approver rejection the system never re-drafts on its own; HR is asked to revise.',
    '',
    '### Approval',
    '- Signed link to the reporting manager (if eligible) or the first eligible approver.',
    '- Level 1 before level 2, never the same person twice, never the offer creator (enforced by the database).',
    '',
    '### Send',
    '- The backend renders the offer letter PDF → `api.mark_offer_sent` (schedules reminders and expiry) → signed response link → email.',
    '',
    '### Afterwards',
    '- Reminders, expiry, negotiation and closure notify the candidate and HR. A response cancels the timers.',
  ), 5],

  'WF-06': [lines(
    '## WF-06 Employee Onboarding',
    '',
    '### START_ONBOARDING (offer accepted)',
    '- `api.create_employee_from_offer` creates the employee **exactly once per offer**, generates the `NT-YYYY-NNN` code and the company email, and creates the tasks from the templates.',
    '- Account provisioning is recorded (`api.mark_account_provisioned`).',
    '- Welcome email to the new employee (first day, orientation), notice to HR, the manager and IT.',
    '',
    '### Hourly sweep',
    '- Also on demand: `POST /webhook/ops/onboarding-sweep` (header auth).',
    '- `api.claim_overdue_onboarding_tasks` claims overdue tasks not reminded within `onboarding.overdue_reminder_every`; each owner is reminded once per claim.',
    '',
    '### NOTIFY_ONBOARDING_COMPLETE',
    '- When the last task is done, HR and the manager are told; the employee gets a closing update from WF-02.',
  ), 5],

  'WF-07': [lines(
    '## WF-07 Error & Recovery',
    '',
    '### 1. Error Trigger',
    '- The error workflow of every NovaTech workflow. A crash is recorded in the error queue (`api.record_error`, deduplicated by fingerprint) and its run is closed as FAILED.',
    '',
    '### 2. Every 5 minutes',
    '- `api.claim_unalerted_errors` → one digest email to `ops.alert_email` (each error is alerted once).',
    '',
    '### 3. Replay',
    '- `POST /webhook/ops/replay` (header auth; called by the backend when staff press Replay).',
    '- `api.begin_error_replay` → re-run the stored payload in the original workflow → `api.resolve_error` marks it RESOLVED or keeps it OPEN.',
    '- Replays reuse the original keys and ids, so they cannot create duplicates.',
  ), 5],

  'WF-08': [lines(
    '## WF-08 Monitoring & Reporting',
    '',
    '### Daily report (09:00 company time)',
    '- On demand: `POST /webhook/ops/daily-report` (header auth) with `{"report_date": "YYYY-MM-DD", "force": false}`.',
    '- Every number comes from `reporting.daily_metrics`. The backend writes the prose (Mistral) and rejects any AI text that contains a number that is not in the metrics.',
    '- One report per date (`api.save_daily_report`), emailed at most once (`report.daily:<date>`).',
    '',
    '### Review alerts (`NOTIFY_REVIEW_QUEUE`)',
    '- Emails recruiters (screening review) or the hiring manager (interview review), after re-checking that the case still needs a person.',
  ), 5],

  'WF-09': [lines(
    '## WF-09 Notification API',
    '`POST /webhook/ops/notify` (header auth, backend only).',
    '',
    '### Body',
    '- `dedupe_key`, `template_key`, `recipient`, `subject`, `html`',
    '- optional `entity_type`, `entity_id`, `application_id`',
    '',
    'The message goes through **SWF-02**: recorded in `ops.notifications`, sent at most once per dedupe key, with the same mail credential as every other email. Used for staff sign-in links.',
  ), 5],

  'SWF-01': [lines(
    '## SWF-01 Backend Call',
    'The only place that knows the backend URL and API key (credential **NovaTech Backend API key**).',
    '',
    '### Retry policy',
    '- **2xx**: return the result.',
    '- `retryable: true`, 429, 408, 5xx or a network error: retry after 2 s, then 4 s (3 attempts). Each retry is logged as RETRY_ATTEMPT, a later success as RETRY_RECOVERED.',
    '- Any other 4xx: no retry.',
    '',
    '### Contract',
    '- Never throws. The caller gets `{ ok, status, body, attempts, error_class, error_code, error_message }` and chooses between a fallback and the error queue (SWF-03).',
    '- `X-Attempt` and `X-Fault-Inject` drive the deterministic failure demos.',
  ), 5],

  'SWF-02': [lines(
    '## SWF-02 Send Notification (at most once)',
    '- `api.begin_notification` claims the dedupe key first; if a replay already sent this message, nothing is sent again.',
    '- The sender is **<company.name> Careers** with the address in the setting `company.careers_email`.',
    '- Only this sub-workflow knows the mail provider: change the SMTP credential and every workflow follows.',
  ), 5],

  'SWF-02-setup': [lines(
    '## Setup: outgoing email (SMTP)',
    'The node **Send Email** uses the credential **NovaTech SMTP (outgoing email)**. Out of the box it points at Mailpit, the local test inbox (http://localhost:8025): nothing reaches real inboxes.',
    '',
    '### To send real email with Gmail',
    '1. In your Google account turn on **2-Step Verification**, then create an **App password** (Security → App passwords).',
    '2. n8n → **Credentials** → **NovaTech SMTP (outgoing email)**:',
    '- **User**: your Gmail address',
    '- **Password**: the 16-character app password',
    '- **Host**: `smtp.gmail.com`, **Port**: `465`, **SSL/TLS**: on',
    '3. Set `MAIL_FROM_ADDRESS` in `.env` to the same Gmail address and run `docker compose up -d seed` (updates `company.careers_email`).',
    '',
    'Any other provider (Outlook, SES, Brevo, ...) works the same way with its SMTP host, port and login.',
  ), 3],

  'SWF-03': [lines(
    '## SWF-03 Fail & Record Error',
    'Called by any workflow on an unrecoverable failure.',
    '1. `api.record_error` stores the error with the original payload and the replay target (deduplicated by fingerprint).',
    '2. `api.finish_workflow_execution` marks the calling execution FAILED.',
    '',
    'Operators see it in the HR portal (**Automation errors**, from `reporting.v_error_queue`) and replay it through WF-07.',
  ), 5],
};
